### ISSUE TITLE
Update 'Welcome' Message

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2022.code4lib.org#29]
During today's meeting, Jerry proposed a rewrite of the welcome message for the Buffalo conference to include SUNY Buffalo or State University of New York at Buffalo... I don't recall the specifics of the language at the moment.

The welcome message can be found in the main `index.html` file in the project's root directory.

**Comment by yarnetsky** [comment]
@dzoladz Draft message in pull request #34

Hopefully it's not too cheezy, but it explains the theme a bit

(additional gems required for me to build repo on a windows machine, feel free to ignore)

**Comment by dzoladz** [comment]
I'm fine with a longer-than-previous-conferences welcome message.

> When Nicola Tesla flipped the switch for the world's first long-range transmission of electricity in 1896, Buffalo became the City of Light. This spirit of innovation glows brighter than ever in Buffalo which makes it the perfect location for our 2022 Code4Lib Conference. Being hosted by the State University of New York at Buffalo, details on our venue are coming soon!

I'll need to confirm that the CSS works properly with a longer text on small screens. I can do that this evening.

Other thoughts?

**Comment by phette23** [comment]
If we're going to be editing the welcome message each year, should it be a config variable? Just a thought, I'm not necessarily into that, it might be awkward if we want to insert a lot of links or other HTML. As is, I think the new text is a big improvement.

There definitely are some responsiveness problems in the range of <1000px width to before the phone-sized screen breakpoint where the star image is on its own line. The text overlaps the image in between those breakpoints.

<img width="685" alt="Screen Shot 2021-11-08 at 1 53 21 PM" src="https://user-images.githubusercontent.com/1024833/140824448-1a4c4c40-5326-4edd-9d20-55f0106f4d5f.png">

**Comment by yarnetsky** [comment]
Yep, this is a draft. At this point, I was wondering if this is even the type  of message that could be envisioned here as it'd not been done before. If so I still need to tweak it, then I figure out how the css for the section works.

Offloading it to a variable makes good sense to me.

**Comment by dzoladz** [comment]
@yarnetsky I'll let you poke around with this a little more. Feel free to reach out if you want some help with it.

**Comment by yarnetsky** [comment]
I got the wording to flow better, and remembered the bootstrap class I was trying to recall so the section now responsive. Also moved the the catchline and welcome message to the conf.yml file under the venue section so it should all be editable in one shot.

**Comment by phette23** [comment]
I get a build error because of the unescaped apostrophe in `venue.welcome-message` but otherwise this looks good and I did some responsiveness testing and it looked good at any window width. For the `welcome-message`, YAML lets you just not use quotes to wrap text fields so I'd do that:

```yml
venue:
    reserved-room-block: false
    name: ' '
   ...
    with-tax-cost: ''
    cost-cutoff-date: 2021-01-01
    welcome-message: In 1896, when Nicola Tesla initiated the world's first long-range transmission of electricity, Buffalo became the City of Light. Today, from biomedical research to the arts, this spirit of innovation glows brighter than ever, which makes Buffalo a perfect location for our 2022 Code4Lib Conference. Hosted by the State University of New York at Buffalo, details on our venue are coming soon!
    catchline: 'the City of Light'
```
